name: Go
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 5 * * *'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out ./...

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.5
      with:
          infile: coverage.out
          outfile: coverage.lcov

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
