name: action-tests
on:
  push:
    paths:
      - '**.go'
      - '**.yml'
      - 'go.mod'

jobs:

  test:
    name: Test on go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.13, 1.14, 1.15, 1.16, 1.17]

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Use Go ${{ matrix.go_version }}
      timeout-minutes: 3
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
#      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run tests
      run: go test -v -cover ./...
